// <auto-generated />
namespace __NAME__.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    public sealed partial class log4net : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(log4net));

        string IMigrationMetadata.Id
        {
            get { return "201303082032300_log4net"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
